library(data.table)
if(!file.exists("power.zip")) download.file("https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip", "power.zip")
unzip("power.zip")
data <- fread("household_power_consumption.txt", sep=";", colClasses = c("factor","factor","factor","factor","factor","factor","factor","factor","factor"), na.strings=c("","?"))
data <- subset(data,data$Date == "1/2/2007" | data$Date == "2/2/2007")
data$DateTime <- as.POSIXct(strptime(paste(data$Date, data$Time), format="%d/%m/%Y %H:%M:%S"))
data$Global_active_power <- as.numeric(data$Global_active_power)
data$Global_reactive_power <- as.numeric(data$Global_reactive_power)
data$Voltage <- as.numeric(data$Voltage)
data$Global_intensity <- as.numeric(data$Global_intensity)
data$Sub_metering_1 <- as.numeric(data$Sub_metering_1)
data$Sub_metering_2 <- as.numeric(data$Sub_metering_2)